//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int id_matricula { get; set; }
        public string nombre_estudiante { get; set; }
        public string cedula_estudiante { get; set; }
        public string escuela_procedencia { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string telefono_estudiante { get; set; }
        public string nivel { get; set; }
        public string nombre_padre { get; set; }
        public string cedula_padre { get; set; }
        public string telefono_padre { get; set; }
        public string direccion_padre { get; set; }
        public string parentesco { get; set; }
        public Nullable<System.DateTime> fecha_cita { get; set; }
        public string hora_cita { get; set; }
    }
}
