//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int id_matricula { get; set; }
        public string nombre_estudiante { get; set; }
        public string cedula_estudiante { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string genero { get; set; }
        public string nacionalidad_estudiante { get; set; }
        public string lugar_nacimiento { get; set; }
        public string tipo_agrupamiento { get; set; }
        public string modalidad_ingreso { get; set; }
        public string escuela_procedencia { get; set; }
        public string distrito_donde_vive { get; set; }
        public string pueblo_donde_vive { get; set; }
        public string telefono_estudiante { get; set; }
        public string correo_electronico_estudiante { get; set; }
        public string nivel_academico { get; set; }
        public string grado_academico { get; set; }
        public string modalidad_academica { get; set; }
        public Nullable<bool> recibe_ayuda_economica { get; set; }
        public string tipo_ayuda { get; set; }
        public string nombre_madre { get; set; }
        public string cedula_madre { get; set; }
        public string nacionalidad_madre { get; set; }
        public string telefono_madre { get; set; }
        public string escolaridad_madre { get; set; }
        public string direccion_madre { get; set; }
        public string nombre_padre { get; set; }
        public string cedula_padre { get; set; }
        public string nacionalidad_padre { get; set; }
        public string telefono_padre { get; set; }
        public string escolaridad_padre { get; set; }
        public string direccion_padre { get; set; }
        public string nombre_encargado { get; set; }
        public string cedula_encargado { get; set; }
        public string nacionalidad_encargado { get; set; }
        public string telefono_encargado { get; set; }
        public string escolaridad_encargado { get; set; }
        public string direccion_encargado { get; set; }
        public string autorizados_nombre1 { get; set; }
        public string autorizados_cedula1 { get; set; }
        public string autorizados_telefono1 { get; set; }
        public string autorizados_nombre2 { get; set; }
        public string autorizados_cedula2 { get; set; }
        public string autorizados_telefono2 { get; set; }
        public string autorizados_nombre3 { get; set; }
        public string autorizados_cedula3 { get; set; }
        public string autorizados_telefono3 { get; set; }
        public Nullable<bool> permiso_educacion_religiosa { get; set; }
        public Nullable<bool> permiso_salidas_libres { get; set; }
        public Nullable<bool> permiso_imagenes { get; set; }
        public Nullable<bool> permiso_autoriza_otro_retirar { get; set; }
        public string comentario_adicional { get; set; }
        public string firma_padre_madre { get; set; }
        public string cedula_firma { get; set; }
        public string nombre_funcionario { get; set; }
        public Nullable<System.DateTime> fecha_firma { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    }
}
