//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int id_nota { get; set; }
        public int id_estudiante { get; set; }
        public int id_materia { get; set; }
        public int id_profesor { get; set; }
        public int id_tipo_nota { get; set; }
        public decimal nota1 { get; set; }
        public string observaciones { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual Profesore Profesore { get; set; }
        public virtual TiposNota TiposNota { get; set; }
    }
}
