//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public int id_noticia { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public System.DateTime fecha_publicacion { get; set; }
        public string imagen_url { get; set; }
    }
}
