//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id_usuario { get; set; }
        public string usuario1 { get; set; }
        public string contrasena { get; set; }
        public string rol { get; set; }
        public Nullable<int> id_estudiante { get; set; }
        public Nullable<int> id_profesor { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Profesore Profesore { get; set; }
    }
}
