//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Entidades;
    
    public partial class L_BAEntities : DbContext
    {
        public L_BAEntities()
            : base("name=L_BAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asistencia> Asistencias { get; set; }
        public virtual DbSet<Ciclo> Ciclos { get; set; }
        public virtual DbSet<Estados_Asistencia> Estados_Asistencia { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Matricula> Matriculas { get; set; }
        public virtual DbSet<Nota> Notas { get; set; }
        public virtual DbSet<Notas_Estandarizadas> Notas_Estandarizadas { get; set; }
        public virtual DbSet<NotasEstandarizada> NotasEstandarizadas { get; set; }
        public virtual DbSet<Padre> Padres { get; set; }
        public virtual DbSet<Profesore> Profesores { get; set; }
        public virtual DbSet<Seccione> Secciones { get; set; }
        public virtual DbSet<TiposNota> TiposNotas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<vista_asistencia_detalle> vista_asistencia_detalle { get; set; }
        public virtual DbSet<vista_estudiantes_info> vista_estudiantes_info { get; set; }
        public virtual DbSet<vista_notas_estudiantes> vista_notas_estudiantes { get; set; }
    
        public virtual int SP_asignarEstudianteAPadre(Nullable<int> id_padre, Nullable<int> id_estudiante)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_asignarEstudianteAPadre", id_padreParameter, id_estudianteParameter);
        }
    
        public virtual int SP_asignarMateriaAProfesor(Nullable<int> id_profesor, Nullable<int> id_materia)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_asignarMateriaAProfesor", id_profesorParameter, id_materiaParameter);
        }
    
        public virtual int SP_delAsistencia(Nullable<int> id_asistencia)
        {
            var id_asistenciaParameter = id_asistencia.HasValue ?
                new ObjectParameter("id_asistencia", id_asistencia) :
                new ObjectParameter("id_asistencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delAsistencia", id_asistenciaParameter);
        }
    
        public virtual int SP_delAsistenciaPorFecha(Nullable<int> id_estudiante, Nullable<System.DateTime> fecha, Nullable<int> id_profesor, Nullable<int> id_materia)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delAsistenciaPorFecha", id_estudianteParameter, fechaParameter, id_profesorParameter, id_materiaParameter);
        }
    
        public virtual int SP_delCiclo(Nullable<int> id_ciclo)
        {
            var id_cicloParameter = id_ciclo.HasValue ?
                new ObjectParameter("id_ciclo", id_ciclo) :
                new ObjectParameter("id_ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delCiclo", id_cicloParameter);
        }
    
        public virtual int SP_delEstudiante(Nullable<int> id_estudiante)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delEstudiante", id_estudianteParameter);
        }
    
        public virtual int SP_delMateria(Nullable<int> id_materia)
        {
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delMateria", id_materiaParameter);
        }
    
        public virtual int SP_delNota(Nullable<int> id_nota)
        {
            var id_notaParameter = id_nota.HasValue ?
                new ObjectParameter("id_nota", id_nota) :
                new ObjectParameter("id_nota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delNota", id_notaParameter);
        }
    
        public virtual int SP_delPadre(Nullable<int> id_padre)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delPadre", id_padreParameter);
        }
    
        public virtual int SP_delProfesor(Nullable<int> id_profesor)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delProfesor", id_profesorParameter);
        }
    
        public virtual int SP_delSeccion(Nullable<int> id_seccion)
        {
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delSeccion", id_seccionParameter);
        }
    
        public virtual int SP_delUsuario(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delUsuario", id_usuarioParameter);
        }
    
        public virtual int SP_insAsistencia(Nullable<int> id_estudiante, Nullable<int> id_materia, Nullable<int> id_profesor, Nullable<System.DateTime> fecha, Nullable<int> id_estado, string observaciones)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var id_estadoParameter = id_estado.HasValue ?
                new ObjectParameter("id_estado", id_estado) :
                new ObjectParameter("id_estado", typeof(int));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insAsistencia", id_estudianteParameter, id_materiaParameter, id_profesorParameter, fechaParameter, id_estadoParameter, observacionesParameter);
        }
    
        public virtual int SP_insCiclo(string nombre, string descripcion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insCiclo", nombreParameter, descripcionParameter);
        }
    
        public virtual int SP_insEstudiante(string cedula, string nombre, string direccion, string telefono, Nullable<int> id_seccion)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insEstudiante", cedulaParameter, nombreParameter, direccionParameter, telefonoParameter, id_seccionParameter);
        }
    
        public virtual int SP_insMateria(string nombre_materia)
        {
            var nombre_materiaParameter = nombre_materia != null ?
                new ObjectParameter("nombre_materia", nombre_materia) :
                new ObjectParameter("nombre_materia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insMateria", nombre_materiaParameter);
        }
    
        public virtual int SP_insMatricula(string nombre_estudiante, string cedula_estudiante, Nullable<System.DateTime> fecha_nacimiento, string genero, string nacionalidad_estudiante, string lugar_nacimiento, string tipo_agrupamiento, string modalidad_ingreso, string escuela_procedencia, string distrito_donde_vive, string pueblo_donde_vive, string telefono_estudiante, string correo_electronico_estudiante, string nivel_academico, string grado_academico, string modalidad_academica, Nullable<bool> recibe_ayuda_economica, string tipo_ayuda, string nombre_madre, string cedula_madre, string nacionalidad_madre, string telefono_madre, string escolaridad_madre, string direccion_madre, string nombre_padre, string cedula_padre, string nacionalidad_padre, string telefono_padre, string escolaridad_padre, string direccion_padre, Nullable<bool> permiso_educacion_religiosa, Nullable<bool> permiso_salidas_libres, Nullable<bool> permiso_imagenes, Nullable<bool> permiso_autoriza_otro_retirar, string comentario_adicional, string firma_padre_madre, string cedula_firma, string nombre_funcionario, Nullable<System.DateTime> fecha_firma)
        {
            var nombre_estudianteParameter = nombre_estudiante != null ?
                new ObjectParameter("nombre_estudiante", nombre_estudiante) :
                new ObjectParameter("nombre_estudiante", typeof(string));
    
            var cedula_estudianteParameter = cedula_estudiante != null ?
                new ObjectParameter("cedula_estudiante", cedula_estudiante) :
                new ObjectParameter("cedula_estudiante", typeof(string));
    
            var fecha_nacimientoParameter = fecha_nacimiento.HasValue ?
                new ObjectParameter("fecha_nacimiento", fecha_nacimiento) :
                new ObjectParameter("fecha_nacimiento", typeof(System.DateTime));
    
            var generoParameter = genero != null ?
                new ObjectParameter("genero", genero) :
                new ObjectParameter("genero", typeof(string));
    
            var nacionalidad_estudianteParameter = nacionalidad_estudiante != null ?
                new ObjectParameter("nacionalidad_estudiante", nacionalidad_estudiante) :
                new ObjectParameter("nacionalidad_estudiante", typeof(string));
    
            var lugar_nacimientoParameter = lugar_nacimiento != null ?
                new ObjectParameter("lugar_nacimiento", lugar_nacimiento) :
                new ObjectParameter("lugar_nacimiento", typeof(string));
    
            var tipo_agrupamientoParameter = tipo_agrupamiento != null ?
                new ObjectParameter("tipo_agrupamiento", tipo_agrupamiento) :
                new ObjectParameter("tipo_agrupamiento", typeof(string));
    
            var modalidad_ingresoParameter = modalidad_ingreso != null ?
                new ObjectParameter("modalidad_ingreso", modalidad_ingreso) :
                new ObjectParameter("modalidad_ingreso", typeof(string));
    
            var escuela_procedenciaParameter = escuela_procedencia != null ?
                new ObjectParameter("escuela_procedencia", escuela_procedencia) :
                new ObjectParameter("escuela_procedencia", typeof(string));
    
            var distrito_donde_viveParameter = distrito_donde_vive != null ?
                new ObjectParameter("distrito_donde_vive", distrito_donde_vive) :
                new ObjectParameter("distrito_donde_vive", typeof(string));
    
            var pueblo_donde_viveParameter = pueblo_donde_vive != null ?
                new ObjectParameter("pueblo_donde_vive", pueblo_donde_vive) :
                new ObjectParameter("pueblo_donde_vive", typeof(string));
    
            var telefono_estudianteParameter = telefono_estudiante != null ?
                new ObjectParameter("telefono_estudiante", telefono_estudiante) :
                new ObjectParameter("telefono_estudiante", typeof(string));
    
            var correo_electronico_estudianteParameter = correo_electronico_estudiante != null ?
                new ObjectParameter("correo_electronico_estudiante", correo_electronico_estudiante) :
                new ObjectParameter("correo_electronico_estudiante", typeof(string));
    
            var nivel_academicoParameter = nivel_academico != null ?
                new ObjectParameter("nivel_academico", nivel_academico) :
                new ObjectParameter("nivel_academico", typeof(string));
    
            var grado_academicoParameter = grado_academico != null ?
                new ObjectParameter("grado_academico", grado_academico) :
                new ObjectParameter("grado_academico", typeof(string));
    
            var modalidad_academicaParameter = modalidad_academica != null ?
                new ObjectParameter("modalidad_academica", modalidad_academica) :
                new ObjectParameter("modalidad_academica", typeof(string));
    
            var recibe_ayuda_economicaParameter = recibe_ayuda_economica.HasValue ?
                new ObjectParameter("recibe_ayuda_economica", recibe_ayuda_economica) :
                new ObjectParameter("recibe_ayuda_economica", typeof(bool));
    
            var tipo_ayudaParameter = tipo_ayuda != null ?
                new ObjectParameter("tipo_ayuda", tipo_ayuda) :
                new ObjectParameter("tipo_ayuda", typeof(string));
    
            var nombre_madreParameter = nombre_madre != null ?
                new ObjectParameter("nombre_madre", nombre_madre) :
                new ObjectParameter("nombre_madre", typeof(string));
    
            var cedula_madreParameter = cedula_madre != null ?
                new ObjectParameter("cedula_madre", cedula_madre) :
                new ObjectParameter("cedula_madre", typeof(string));
    
            var nacionalidad_madreParameter = nacionalidad_madre != null ?
                new ObjectParameter("nacionalidad_madre", nacionalidad_madre) :
                new ObjectParameter("nacionalidad_madre", typeof(string));
    
            var telefono_madreParameter = telefono_madre != null ?
                new ObjectParameter("telefono_madre", telefono_madre) :
                new ObjectParameter("telefono_madre", typeof(string));
    
            var escolaridad_madreParameter = escolaridad_madre != null ?
                new ObjectParameter("escolaridad_madre", escolaridad_madre) :
                new ObjectParameter("escolaridad_madre", typeof(string));
    
            var direccion_madreParameter = direccion_madre != null ?
                new ObjectParameter("direccion_madre", direccion_madre) :
                new ObjectParameter("direccion_madre", typeof(string));
    
            var nombre_padreParameter = nombre_padre != null ?
                new ObjectParameter("nombre_padre", nombre_padre) :
                new ObjectParameter("nombre_padre", typeof(string));
    
            var cedula_padreParameter = cedula_padre != null ?
                new ObjectParameter("cedula_padre", cedula_padre) :
                new ObjectParameter("cedula_padre", typeof(string));
    
            var nacionalidad_padreParameter = nacionalidad_padre != null ?
                new ObjectParameter("nacionalidad_padre", nacionalidad_padre) :
                new ObjectParameter("nacionalidad_padre", typeof(string));
    
            var telefono_padreParameter = telefono_padre != null ?
                new ObjectParameter("telefono_padre", telefono_padre) :
                new ObjectParameter("telefono_padre", typeof(string));
    
            var escolaridad_padreParameter = escolaridad_padre != null ?
                new ObjectParameter("escolaridad_padre", escolaridad_padre) :
                new ObjectParameter("escolaridad_padre", typeof(string));
    
            var direccion_padreParameter = direccion_padre != null ?
                new ObjectParameter("direccion_padre", direccion_padre) :
                new ObjectParameter("direccion_padre", typeof(string));
    
            var permiso_educacion_religiosaParameter = permiso_educacion_religiosa.HasValue ?
                new ObjectParameter("permiso_educacion_religiosa", permiso_educacion_religiosa) :
                new ObjectParameter("permiso_educacion_religiosa", typeof(bool));
    
            var permiso_salidas_libresParameter = permiso_salidas_libres.HasValue ?
                new ObjectParameter("permiso_salidas_libres", permiso_salidas_libres) :
                new ObjectParameter("permiso_salidas_libres", typeof(bool));
    
            var permiso_imagenesParameter = permiso_imagenes.HasValue ?
                new ObjectParameter("permiso_imagenes", permiso_imagenes) :
                new ObjectParameter("permiso_imagenes", typeof(bool));
    
            var permiso_autoriza_otro_retirarParameter = permiso_autoriza_otro_retirar.HasValue ?
                new ObjectParameter("permiso_autoriza_otro_retirar", permiso_autoriza_otro_retirar) :
                new ObjectParameter("permiso_autoriza_otro_retirar", typeof(bool));
    
            var comentario_adicionalParameter = comentario_adicional != null ?
                new ObjectParameter("comentario_adicional", comentario_adicional) :
                new ObjectParameter("comentario_adicional", typeof(string));
    
            var firma_padre_madreParameter = firma_padre_madre != null ?
                new ObjectParameter("firma_padre_madre", firma_padre_madre) :
                new ObjectParameter("firma_padre_madre", typeof(string));
    
            var cedula_firmaParameter = cedula_firma != null ?
                new ObjectParameter("cedula_firma", cedula_firma) :
                new ObjectParameter("cedula_firma", typeof(string));
    
            var nombre_funcionarioParameter = nombre_funcionario != null ?
                new ObjectParameter("nombre_funcionario", nombre_funcionario) :
                new ObjectParameter("nombre_funcionario", typeof(string));
    
            var fecha_firmaParameter = fecha_firma.HasValue ?
                new ObjectParameter("fecha_firma", fecha_firma) :
                new ObjectParameter("fecha_firma", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insMatricula", nombre_estudianteParameter, cedula_estudianteParameter, fecha_nacimientoParameter, generoParameter, nacionalidad_estudianteParameter, lugar_nacimientoParameter, tipo_agrupamientoParameter, modalidad_ingresoParameter, escuela_procedenciaParameter, distrito_donde_viveParameter, pueblo_donde_viveParameter, telefono_estudianteParameter, correo_electronico_estudianteParameter, nivel_academicoParameter, grado_academicoParameter, modalidad_academicaParameter, recibe_ayuda_economicaParameter, tipo_ayudaParameter, nombre_madreParameter, cedula_madreParameter, nacionalidad_madreParameter, telefono_madreParameter, escolaridad_madreParameter, direccion_madreParameter, nombre_padreParameter, cedula_padreParameter, nacionalidad_padreParameter, telefono_padreParameter, escolaridad_padreParameter, direccion_padreParameter, permiso_educacion_religiosaParameter, permiso_salidas_libresParameter, permiso_imagenesParameter, permiso_autoriza_otro_retirarParameter, comentario_adicionalParameter, firma_padre_madreParameter, cedula_firmaParameter, nombre_funcionarioParameter, fecha_firmaParameter);
        }
    
        public virtual int SP_insNota(Nullable<int> id_estudiante, Nullable<int> id_materia, Nullable<int> id_profesor, Nullable<int> id_tipo_nota, Nullable<decimal> nota, string observaciones, Nullable<System.DateTime> fecha)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var id_tipo_notaParameter = id_tipo_nota.HasValue ?
                new ObjectParameter("id_tipo_nota", id_tipo_nota) :
                new ObjectParameter("id_tipo_nota", typeof(int));
    
            var notaParameter = nota.HasValue ?
                new ObjectParameter("nota", nota) :
                new ObjectParameter("nota", typeof(decimal));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insNota", id_estudianteParameter, id_materiaParameter, id_profesorParameter, id_tipo_notaParameter, notaParameter, observacionesParameter, fechaParameter);
        }
    
        public virtual int SP_insNotaEstandarizada(Nullable<int> id_estudiante, Nullable<int> id_materia, Nullable<int> id_profesor, Nullable<decimal> nota, string observaciones, Nullable<System.DateTime> fecha)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var notaParameter = nota.HasValue ?
                new ObjectParameter("nota", nota) :
                new ObjectParameter("nota", typeof(decimal));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insNotaEstandarizada", id_estudianteParameter, id_materiaParameter, id_profesorParameter, notaParameter, observacionesParameter, fechaParameter);
        }
    
        public virtual int SP_insPadre(string cedula, string nombre, string telefono)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insPadre", cedulaParameter, nombreParameter, telefonoParameter);
        }
    
        public virtual int SP_insProfesor(string cedula, string nombre)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insProfesor", cedulaParameter, nombreParameter);
        }
    
        public virtual int SP_insSeccion(string nombre, Nullable<int> id_ciclo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_cicloParameter = id_ciclo.HasValue ?
                new ObjectParameter("id_ciclo", id_ciclo) :
                new ObjectParameter("id_ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insSeccion", nombreParameter, id_cicloParameter);
        }
    
        public virtual int SP_insTipoNota(string nombre_tipo)
        {
            var nombre_tipoParameter = nombre_tipo != null ?
                new ObjectParameter("nombre_tipo", nombre_tipo) :
                new ObjectParameter("nombre_tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insTipoNota", nombre_tipoParameter);
        }
    
        public virtual int SP_insUsuario(string usuario, string contrasena, string rol, Nullable<int> id_estudiante, Nullable<int> id_profesor)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            var rolParameter = rol != null ?
                new ObjectParameter("rol", rol) :
                new ObjectParameter("rol", typeof(string));
    
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insUsuario", usuarioParameter, contrasenaParameter, rolParameter, id_estudianteParameter, id_profesorParameter);
        }
    
        public virtual int SP_modAsistencia(Nullable<int> id_asistencia, Nullable<int> id_estado, string observaciones)
        {
            var id_asistenciaParameter = id_asistencia.HasValue ?
                new ObjectParameter("id_asistencia", id_asistencia) :
                new ObjectParameter("id_asistencia", typeof(int));
    
            var id_estadoParameter = id_estado.HasValue ?
                new ObjectParameter("id_estado", id_estado) :
                new ObjectParameter("id_estado", typeof(int));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modAsistencia", id_asistenciaParameter, id_estadoParameter, observacionesParameter);
        }
    
        public virtual int SP_modCiclo(Nullable<int> id_ciclo, string nombre, string descripcion)
        {
            var id_cicloParameter = id_ciclo.HasValue ?
                new ObjectParameter("id_ciclo", id_ciclo) :
                new ObjectParameter("id_ciclo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modCiclo", id_cicloParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int SP_modEstudiante(Nullable<int> id_estudiante, string cedula, string nombre, string direccion, string telefono, Nullable<int> id_seccion)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modEstudiante", id_estudianteParameter, cedulaParameter, nombreParameter, direccionParameter, telefonoParameter, id_seccionParameter);
        }
    
        public virtual int SP_modMateria(Nullable<int> id_materia, string nombre_materia)
        {
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            var nombre_materiaParameter = nombre_materia != null ?
                new ObjectParameter("nombre_materia", nombre_materia) :
                new ObjectParameter("nombre_materia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modMateria", id_materiaParameter, nombre_materiaParameter);
        }
    
        public virtual int SP_modNota(Nullable<int> id_nota, Nullable<decimal> nota, string observaciones, Nullable<System.DateTime> fecha)
        {
            var id_notaParameter = id_nota.HasValue ?
                new ObjectParameter("id_nota", id_nota) :
                new ObjectParameter("id_nota", typeof(int));
    
            var notaParameter = nota.HasValue ?
                new ObjectParameter("nota", nota) :
                new ObjectParameter("nota", typeof(decimal));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("observaciones", observaciones) :
                new ObjectParameter("observaciones", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modNota", id_notaParameter, notaParameter, observacionesParameter, fechaParameter);
        }
    
        public virtual int SP_modPadre(Nullable<int> id_padre, string cedula, string nombre, string telefono)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modPadre", id_padreParameter, cedulaParameter, nombreParameter, telefonoParameter);
        }
    
        public virtual int SP_modProfesor(Nullable<int> id_profesor, string cedula, string nombre)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modProfesor", id_profesorParameter, cedulaParameter, nombreParameter);
        }
    
        public virtual int SP_modSeccion(Nullable<int> id_seccion, string nombre, Nullable<int> id_ciclo)
        {
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_cicloParameter = id_ciclo.HasValue ?
                new ObjectParameter("id_ciclo", id_ciclo) :
                new ObjectParameter("id_ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modSeccion", id_seccionParameter, nombreParameter, id_cicloParameter);
        }
    
        public virtual int SP_modUsuario(Nullable<int> id_usuario, string usuario, string contrasena, string rol, Nullable<bool> activo)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            var rolParameter = rol != null ?
                new ObjectParameter("rol", rol) :
                new ObjectParameter("rol", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modUsuario", id_usuarioParameter, usuarioParameter, contrasenaParameter, rolParameter, activoParameter);
        }
    
        public virtual int SP_quitarEstudianteDePadre(Nullable<int> id_padre, Nullable<int> id_estudiante)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_quitarEstudianteDePadre", id_padreParameter, id_estudianteParameter);
        }
    
        public virtual int SP_quitarMateriaDeProfesor(Nullable<int> id_profesor, Nullable<int> id_materia)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_quitarMateriaDeProfesor", id_profesorParameter, id_materiaParameter);
        }
    
        public virtual ObjectResult<SP_recAsistenciaPorId_Result> SP_recAsistenciaPorId(Nullable<int> id_asistencia)
        {
            var id_asistenciaParameter = id_asistencia.HasValue ?
                new ObjectParameter("id_asistencia", id_asistencia) :
                new ObjectParameter("id_asistencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recAsistenciaPorId_Result>("SP_recAsistenciaPorId", id_asistenciaParameter);
        }
    
        public virtual ObjectResult<SP_recAsistencias_Result> SP_recAsistencias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recAsistencias_Result>("SP_recAsistencias");
        }
    
        public virtual ObjectResult<SP_recCicloPorId_Result> SP_recCicloPorId(Nullable<int> id_ciclo)
        {
            var id_cicloParameter = id_ciclo.HasValue ?
                new ObjectParameter("id_ciclo", id_ciclo) :
                new ObjectParameter("id_ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recCicloPorId_Result>("SP_recCicloPorId", id_cicloParameter);
        }
    
        public virtual ObjectResult<SP_recCiclos_Result> SP_recCiclos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recCiclos_Result>("SP_recCiclos");
        }
    
        public virtual ObjectResult<SP_recEstadosAsistencia_Result> SP_recEstadosAsistencia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recEstadosAsistencia_Result>("SP_recEstadosAsistencia");
        }
    
        public virtual ObjectResult<SP_recEstudiantePorCedula_Result> SP_recEstudiantePorCedula(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recEstudiantePorCedula_Result>("SP_recEstudiantePorCedula", cedulaParameter);
        }
    
        public virtual ObjectResult<SP_recEstudiantePorId_Result> SP_recEstudiantePorId(Nullable<int> id_estudiante)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recEstudiantePorId_Result>("SP_recEstudiantePorId", id_estudianteParameter);
        }
    
        public virtual ObjectResult<SP_recEstudiantes_Result> SP_recEstudiantes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recEstudiantes_Result>("SP_recEstudiantes");
        }
    
        public virtual ObjectResult<SP_recEstudiantesPorPadre_Result> SP_recEstudiantesPorPadre(Nullable<int> id_padre)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recEstudiantesPorPadre_Result>("SP_recEstudiantesPorPadre", id_padreParameter);
        }
    
        public virtual ObjectResult<SP_recEstudiantesPorSeccion_Result> SP_recEstudiantesPorSeccion(Nullable<int> id_seccion)
        {
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recEstudiantesPorSeccion_Result>("SP_recEstudiantesPorSeccion", id_seccionParameter);
        }
    
        public virtual ObjectResult<SP_recMateriaPorId_Result> SP_recMateriaPorId(Nullable<int> id_materia)
        {
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recMateriaPorId_Result>("SP_recMateriaPorId", id_materiaParameter);
        }
    
        public virtual ObjectResult<SP_recMaterias_Result> SP_recMaterias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recMaterias_Result>("SP_recMaterias");
        }
    
        public virtual ObjectResult<SP_recMateriasConProfesores_Result> SP_recMateriasConProfesores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recMateriasConProfesores_Result>("SP_recMateriasConProfesores");
        }
    
        public virtual ObjectResult<SP_recMateriasPorProfesor_Result> SP_recMateriasPorProfesor(Nullable<int> id_profesor)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recMateriasPorProfesor_Result>("SP_recMateriasPorProfesor", id_profesorParameter);
        }
    
        public virtual ObjectResult<SP_recNotaPorId_Result> SP_recNotaPorId(Nullable<int> id_nota)
        {
            var id_notaParameter = id_nota.HasValue ?
                new ObjectParameter("id_nota", id_nota) :
                new ObjectParameter("id_nota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recNotaPorId_Result>("SP_recNotaPorId", id_notaParameter);
        }
    
        public virtual ObjectResult<SP_recNotas_Result> SP_recNotas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recNotas_Result>("SP_recNotas");
        }
    
        public virtual ObjectResult<SP_recNotasEstandarizadas_Result> SP_recNotasEstandarizadas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recNotasEstandarizadas_Result>("SP_recNotasEstandarizadas");
        }
    
        public virtual ObjectResult<SP_recNotasEstandarizadasPorEstudiante_Result> SP_recNotasEstandarizadasPorEstudiante(Nullable<int> id_estudiante)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recNotasEstandarizadasPorEstudiante_Result>("SP_recNotasEstandarizadasPorEstudiante", id_estudianteParameter);
        }
    
        public virtual ObjectResult<SP_recNotasPorEstudiante_Result> SP_recNotasPorEstudiante(Nullable<int> id_estudiante)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recNotasPorEstudiante_Result>("SP_recNotasPorEstudiante", id_estudianteParameter);
        }
    
        public virtual int SP_recNotasPorMateria(Nullable<int> id_materia)
        {
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_recNotasPorMateria", id_materiaParameter);
        }
    
        public virtual int SP_recNotasPorProfesor(Nullable<int> id_profesor)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_recNotasPorProfesor", id_profesorParameter);
        }
    
        public virtual ObjectResult<SP_recPadrePorCedula_Result> SP_recPadrePorCedula(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recPadrePorCedula_Result>("SP_recPadrePorCedula", cedulaParameter);
        }
    
        public virtual ObjectResult<SP_recPadrePorId_Result> SP_recPadrePorId(Nullable<int> id_padre)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recPadrePorId_Result>("SP_recPadrePorId", id_padreParameter);
        }
    
        public virtual ObjectResult<SP_recPadres_Result> SP_recPadres()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recPadres_Result>("SP_recPadres");
        }
    
        public virtual ObjectResult<SP_recPadresPorEstudiante_Result> SP_recPadresPorEstudiante(Nullable<int> id_estudiante)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recPadresPorEstudiante_Result>("SP_recPadresPorEstudiante", id_estudianteParameter);
        }
    
        public virtual ObjectResult<SP_recProfesores_Result> SP_recProfesores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recProfesores_Result>("SP_recProfesores");
        }
    
        public virtual ObjectResult<SP_recProfesoresConMaterias_Result> SP_recProfesoresConMaterias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recProfesoresConMaterias_Result>("SP_recProfesoresConMaterias");
        }
    
        public virtual ObjectResult<SP_recProfesoresPorMateria_Result> SP_recProfesoresPorMateria(Nullable<int> id_materia)
        {
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recProfesoresPorMateria_Result>("SP_recProfesoresPorMateria", id_materiaParameter);
        }
    
        public virtual ObjectResult<SP_recProfesorPorCedula_Result> SP_recProfesorPorCedula(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recProfesorPorCedula_Result>("SP_recProfesorPorCedula", cedulaParameter);
        }
    
        public virtual ObjectResult<SP_recProfesorPorId_Result> SP_recProfesorPorId(Nullable<int> id_profesor)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recProfesorPorId_Result>("SP_recProfesorPorId", id_profesorParameter);
        }
    
        public virtual ObjectResult<SP_recSecciones_Result> SP_recSecciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recSecciones_Result>("SP_recSecciones");
        }
    
        public virtual ObjectResult<SP_recSeccionesPorCiclo_Result> SP_recSeccionesPorCiclo(Nullable<int> id_ciclo)
        {
            var id_cicloParameter = id_ciclo.HasValue ?
                new ObjectParameter("id_ciclo", id_ciclo) :
                new ObjectParameter("id_ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recSeccionesPorCiclo_Result>("SP_recSeccionesPorCiclo", id_cicloParameter);
        }
    
        public virtual ObjectResult<SP_recSeccionPorId_Result> SP_recSeccionPorId(Nullable<int> id_seccion)
        {
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recSeccionPorId_Result>("SP_recSeccionPorId", id_seccionParameter);
        }
    
        public virtual ObjectResult<SP_recUsuarioPorId_Result> SP_recUsuarioPorId(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recUsuarioPorId_Result>("SP_recUsuarioPorId", id_usuarioParameter);
        }
    
        public virtual ObjectResult<SP_recUsuarios_Result> SP_recUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recUsuarios_Result>("SP_recUsuarios");
        }
    
        public virtual int SP_reporteAsistenciaPorSeccion(Nullable<int> id_seccion)
        {
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_reporteAsistenciaPorSeccion", id_seccionParameter);
        }
    
        public virtual ObjectResult<SP_reporteMensualAsistencia_Result> SP_reporteMensualAsistencia(Nullable<int> anio, Nullable<int> mes, Nullable<int> idProfesor, Nullable<int> idSeccion, Nullable<int> idMateria)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("idProfesor", idProfesor) :
                new ObjectParameter("idProfesor", typeof(int));
    
            var idSeccionParameter = idSeccion.HasValue ?
                new ObjectParameter("idSeccion", idSeccion) :
                new ObjectParameter("idSeccion", typeof(int));
    
            var idMateriaParameter = idMateria.HasValue ?
                new ObjectParameter("idMateria", idMateria) :
                new ObjectParameter("idMateria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_reporteMensualAsistencia_Result>("SP_reporteMensualAsistencia", anioParameter, mesParameter, idProfesorParameter, idSeccionParameter, idMateriaParameter);
        }
    }
}
