//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Entidades;
    
    public partial class L_BAEntities : DbContext
    {
        public L_BAEntities()
            : base("name=L_BAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciclo> Ciclos { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Matricula> Matriculas { get; set; }
        public virtual DbSet<Noticia> Noticias { get; set; }
        public virtual DbSet<Padre> Padres { get; set; }
        public virtual DbSet<Profesore> Profesores { get; set; }
        public virtual DbSet<Seccione> Secciones { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual int SP_asignarEstudianteAPadre(Nullable<int> id_padre, Nullable<int> id_estudiante)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_asignarEstudianteAPadre", id_padreParameter, id_estudianteParameter);
        }
    
        public virtual int SP_asignarMateriaAProfesor(Nullable<int> id_profesor, Nullable<int> id_materia)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_asignarMateriaAProfesor", id_profesorParameter, id_materiaParameter);
        }
    
        public virtual int SP_asignarMateriaProfesor(Nullable<int> id_profesor, Nullable<int> id_materia)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_asignarMateriaProfesor", id_profesorParameter, id_materiaParameter);
        }
    
        public virtual int SP_delCiclo(Nullable<int> id_ciclo)
        {
            var id_cicloParameter = id_ciclo.HasValue ?
                new ObjectParameter("id_ciclo", id_ciclo) :
                new ObjectParameter("id_ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delCiclo", id_cicloParameter);
        }
    
        public virtual int SP_delEstudiante(Nullable<int> id_estudiante)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delEstudiante", id_estudianteParameter);
        }
    
        public virtual int SP_delMateria(Nullable<int> id_materia)
        {
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delMateria", id_materiaParameter);
        }
    
        public virtual int SP_delNoticia(Nullable<int> id_noticia)
        {
            var id_noticiaParameter = id_noticia.HasValue ?
                new ObjectParameter("id_noticia", id_noticia) :
                new ObjectParameter("id_noticia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delNoticia", id_noticiaParameter);
        }
    
        public virtual int SP_delPadre(Nullable<int> id_padre)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delPadre", id_padreParameter);
        }
    
        public virtual int SP_delProfesor(Nullable<int> id_profesor)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delProfesor", id_profesorParameter);
        }
    
        public virtual int SP_delSeccion(Nullable<int> id_seccion)
        {
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delSeccion", id_seccionParameter);
        }
    
        public virtual int SP_delUsuario(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_delUsuario", id_usuarioParameter);
        }
    
        public virtual int SP_insCiclo(string nombre_ciclo, string descripcion)
        {
            var nombre_cicloParameter = nombre_ciclo != null ?
                new ObjectParameter("nombre_ciclo", nombre_ciclo) :
                new ObjectParameter("nombre_ciclo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insCiclo", nombre_cicloParameter, descripcionParameter);
        }
    
        public virtual int SP_insEstudiante(string cedula, string nombre, string direccion, string telefono, Nullable<int> id_seccion)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insEstudiante", cedulaParameter, nombreParameter, direccionParameter, telefonoParameter, id_seccionParameter);
        }
    
        public virtual int SP_insMateria(string nombre_materia)
        {
            var nombre_materiaParameter = nombre_materia != null ?
                new ObjectParameter("nombre_materia", nombre_materia) :
                new ObjectParameter("nombre_materia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insMateria", nombre_materiaParameter);
        }
    
        public virtual int SP_insMatricula(string nombre_estudiante, string cedula_estudiante, string escuela_procedencia, Nullable<System.DateTime> fecha_nacimiento, string telefono_estudiante, string nivel, string nombre_padre, string cedula_padre, string telefono_padre, string direccion_padre, string parentesco, Nullable<System.DateTime> fecha_cita, string hora_cita)
        {
            var nombre_estudianteParameter = nombre_estudiante != null ?
                new ObjectParameter("nombre_estudiante", nombre_estudiante) :
                new ObjectParameter("nombre_estudiante", typeof(string));
    
            var cedula_estudianteParameter = cedula_estudiante != null ?
                new ObjectParameter("cedula_estudiante", cedula_estudiante) :
                new ObjectParameter("cedula_estudiante", typeof(string));
    
            var escuela_procedenciaParameter = escuela_procedencia != null ?
                new ObjectParameter("escuela_procedencia", escuela_procedencia) :
                new ObjectParameter("escuela_procedencia", typeof(string));
    
            var fecha_nacimientoParameter = fecha_nacimiento.HasValue ?
                new ObjectParameter("fecha_nacimiento", fecha_nacimiento) :
                new ObjectParameter("fecha_nacimiento", typeof(System.DateTime));
    
            var telefono_estudianteParameter = telefono_estudiante != null ?
                new ObjectParameter("telefono_estudiante", telefono_estudiante) :
                new ObjectParameter("telefono_estudiante", typeof(string));
    
            var nivelParameter = nivel != null ?
                new ObjectParameter("nivel", nivel) :
                new ObjectParameter("nivel", typeof(string));
    
            var nombre_padreParameter = nombre_padre != null ?
                new ObjectParameter("nombre_padre", nombre_padre) :
                new ObjectParameter("nombre_padre", typeof(string));
    
            var cedula_padreParameter = cedula_padre != null ?
                new ObjectParameter("cedula_padre", cedula_padre) :
                new ObjectParameter("cedula_padre", typeof(string));
    
            var telefono_padreParameter = telefono_padre != null ?
                new ObjectParameter("telefono_padre", telefono_padre) :
                new ObjectParameter("telefono_padre", typeof(string));
    
            var direccion_padreParameter = direccion_padre != null ?
                new ObjectParameter("direccion_padre", direccion_padre) :
                new ObjectParameter("direccion_padre", typeof(string));
    
            var parentescoParameter = parentesco != null ?
                new ObjectParameter("parentesco", parentesco) :
                new ObjectParameter("parentesco", typeof(string));
    
            var fecha_citaParameter = fecha_cita.HasValue ?
                new ObjectParameter("fecha_cita", fecha_cita) :
                new ObjectParameter("fecha_cita", typeof(System.DateTime));
    
            var hora_citaParameter = hora_cita != null ?
                new ObjectParameter("hora_cita", hora_cita) :
                new ObjectParameter("hora_cita", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insMatricula", nombre_estudianteParameter, cedula_estudianteParameter, escuela_procedenciaParameter, fecha_nacimientoParameter, telefono_estudianteParameter, nivelParameter, nombre_padreParameter, cedula_padreParameter, telefono_padreParameter, direccion_padreParameter, parentescoParameter, fecha_citaParameter, hora_citaParameter);
        }
    
        public virtual int SP_insNoticia(string titulo, string contenido, Nullable<System.DateTime> fecha_publicacion, string imagen_url)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var contenidoParameter = contenido != null ?
                new ObjectParameter("contenido", contenido) :
                new ObjectParameter("contenido", typeof(string));
    
            var fecha_publicacionParameter = fecha_publicacion.HasValue ?
                new ObjectParameter("fecha_publicacion", fecha_publicacion) :
                new ObjectParameter("fecha_publicacion", typeof(System.DateTime));
    
            var imagen_urlParameter = imagen_url != null ?
                new ObjectParameter("imagen_url", imagen_url) :
                new ObjectParameter("imagen_url", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insNoticia", tituloParameter, contenidoParameter, fecha_publicacionParameter, imagen_urlParameter);
        }
    
        public virtual int SP_insPadre(string cedula, string nombre, string telefono)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insPadre", cedulaParameter, nombreParameter, telefonoParameter);
        }
    
        public virtual int SP_insProfesor(string cedula, string nombre)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insProfesor", cedulaParameter, nombreParameter);
        }
    
        public virtual int SP_insSeccion(string nombre_seccion, Nullable<int> id_ciclo)
        {
            var nombre_seccionParameter = nombre_seccion != null ?
                new ObjectParameter("nombre_seccion", nombre_seccion) :
                new ObjectParameter("nombre_seccion", typeof(string));
    
            var id_cicloParameter = id_ciclo.HasValue ?
                new ObjectParameter("id_ciclo", id_ciclo) :
                new ObjectParameter("id_ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insSeccion", nombre_seccionParameter, id_cicloParameter);
        }
    
        public virtual int SP_insUsuario(string usuario, string contrasena, string rol, Nullable<int> id_estudiante, Nullable<int> id_profesor)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            var rolParameter = rol != null ?
                new ObjectParameter("rol", rol) :
                new ObjectParameter("rol", typeof(string));
    
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_insUsuario", usuarioParameter, contrasenaParameter, rolParameter, id_estudianteParameter, id_profesorParameter);
        }
    
        public virtual ObjectResult<SP_loginUsuario_Result> SP_loginUsuario(string usuario, string contrasena)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_loginUsuario_Result>("SP_loginUsuario", usuarioParameter, contrasenaParameter);
        }
    
        public virtual int SP_modCiclo(Nullable<int> id_ciclo, string nombre_ciclo, string descripcion)
        {
            var id_cicloParameter = id_ciclo.HasValue ?
                new ObjectParameter("id_ciclo", id_ciclo) :
                new ObjectParameter("id_ciclo", typeof(int));
    
            var nombre_cicloParameter = nombre_ciclo != null ?
                new ObjectParameter("nombre_ciclo", nombre_ciclo) :
                new ObjectParameter("nombre_ciclo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modCiclo", id_cicloParameter, nombre_cicloParameter, descripcionParameter);
        }
    
        public virtual int SP_modEstudiante(Nullable<int> id_estudiante, string cedula, string nombre, string direccion, string telefono, Nullable<int> id_seccion)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modEstudiante", id_estudianteParameter, cedulaParameter, nombreParameter, direccionParameter, telefonoParameter, id_seccionParameter);
        }
    
        public virtual int SP_modMateria(Nullable<int> id_materia, string nombre_materia)
        {
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            var nombre_materiaParameter = nombre_materia != null ?
                new ObjectParameter("nombre_materia", nombre_materia) :
                new ObjectParameter("nombre_materia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modMateria", id_materiaParameter, nombre_materiaParameter);
        }
    
        public virtual int SP_modNoticia(Nullable<int> id_noticia, string titulo, string contenido, Nullable<System.DateTime> fecha_publicacion, string imagen_url)
        {
            var id_noticiaParameter = id_noticia.HasValue ?
                new ObjectParameter("id_noticia", id_noticia) :
                new ObjectParameter("id_noticia", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var contenidoParameter = contenido != null ?
                new ObjectParameter("contenido", contenido) :
                new ObjectParameter("contenido", typeof(string));
    
            var fecha_publicacionParameter = fecha_publicacion.HasValue ?
                new ObjectParameter("fecha_publicacion", fecha_publicacion) :
                new ObjectParameter("fecha_publicacion", typeof(System.DateTime));
    
            var imagen_urlParameter = imagen_url != null ?
                new ObjectParameter("imagen_url", imagen_url) :
                new ObjectParameter("imagen_url", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modNoticia", id_noticiaParameter, tituloParameter, contenidoParameter, fecha_publicacionParameter, imagen_urlParameter);
        }
    
        public virtual int SP_modPadre(Nullable<int> id_padre, string cedula, string nombre, string telefono)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modPadre", id_padreParameter, cedulaParameter, nombreParameter, telefonoParameter);
        }
    
        public virtual int SP_modProfesor(Nullable<int> id_profesor, string cedula, string nombre)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modProfesor", id_profesorParameter, cedulaParameter, nombreParameter);
        }
    
        public virtual int SP_modSeccion(Nullable<int> id_seccion, string nombre_seccion, Nullable<int> id_ciclo)
        {
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            var nombre_seccionParameter = nombre_seccion != null ?
                new ObjectParameter("nombre_seccion", nombre_seccion) :
                new ObjectParameter("nombre_seccion", typeof(string));
    
            var id_cicloParameter = id_ciclo.HasValue ?
                new ObjectParameter("id_ciclo", id_ciclo) :
                new ObjectParameter("id_ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modSeccion", id_seccionParameter, nombre_seccionParameter, id_cicloParameter);
        }
    
        public virtual int SP_modUsuario(Nullable<int> id_usuario, string usuario, string contrasena, string rol, Nullable<bool> activo)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            var rolParameter = rol != null ?
                new ObjectParameter("rol", rol) :
                new ObjectParameter("rol", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_modUsuario", id_usuarioParameter, usuarioParameter, contrasenaParameter, rolParameter, activoParameter);
        }
    
        public virtual int SP_quitarEstudianteDePadre(Nullable<int> id_padre, Nullable<int> id_estudiante)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_quitarEstudianteDePadre", id_padreParameter, id_estudianteParameter);
        }
    
        public virtual int SP_quitarMateriaDeProfesor(Nullable<int> id_profesor, Nullable<int> id_materia)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_quitarMateriaDeProfesor", id_profesorParameter, id_materiaParameter);
        }
    
        public virtual int SP_quitarMateriaProfesor(Nullable<int> id_profesor, Nullable<int> id_materia)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_quitarMateriaProfesor", id_profesorParameter, id_materiaParameter);
        }
    
        public virtual int SP_quitarRelacionPadreEstudiante(Nullable<int> id_padre, Nullable<int> id_estudiante)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_quitarRelacionPadreEstudiante", id_padreParameter, id_estudianteParameter);
        }
    
        public virtual ObjectResult<SP_recCicloPorId_Result> SP_recCicloPorId(Nullable<int> id_ciclo)
        {
            var id_cicloParameter = id_ciclo.HasValue ?
                new ObjectParameter("id_ciclo", id_ciclo) :
                new ObjectParameter("id_ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recCicloPorId_Result>("SP_recCicloPorId", id_cicloParameter);
        }
    
        public virtual ObjectResult<SP_recCiclos_Result> SP_recCiclos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recCiclos_Result>("SP_recCiclos");
        }
    
        public virtual ObjectResult<SP_recEstudiantePorCedula_Result> SP_recEstudiantePorCedula(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recEstudiantePorCedula_Result>("SP_recEstudiantePorCedula", cedulaParameter);
        }
    
        public virtual ObjectResult<SP_recEstudiantePorId_Result> SP_recEstudiantePorId(Nullable<int> id_estudiante)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recEstudiantePorId_Result>("SP_recEstudiantePorId", id_estudianteParameter);
        }
    
        public virtual ObjectResult<SP_recEstudiantes_Result> SP_recEstudiantes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recEstudiantes_Result>("SP_recEstudiantes");
        }
    
        public virtual ObjectResult<SP_recEstudiantesPorPadre_Result> SP_recEstudiantesPorPadre(Nullable<int> id_padre)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recEstudiantesPorPadre_Result>("SP_recEstudiantesPorPadre", id_padreParameter);
        }
    
        public virtual ObjectResult<SP_recEstudiantesPorSeccion_Result> SP_recEstudiantesPorSeccion(Nullable<int> id_seccion)
        {
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recEstudiantesPorSeccion_Result>("SP_recEstudiantesPorSeccion", id_seccionParameter);
        }
    
        public virtual ObjectResult<SP_recMateriaPorId_Result> SP_recMateriaPorId(Nullable<int> id_materia)
        {
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recMateriaPorId_Result>("SP_recMateriaPorId", id_materiaParameter);
        }
    
        public virtual ObjectResult<SP_recMaterias_Result> SP_recMaterias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recMaterias_Result>("SP_recMaterias");
        }
    
        public virtual ObjectResult<SP_recMateriasConProfesores_Result> SP_recMateriasConProfesores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recMateriasConProfesores_Result>("SP_recMateriasConProfesores");
        }
    
        public virtual ObjectResult<SP_recMateriasPorProfesor_Result> SP_recMateriasPorProfesor(Nullable<int> id_profesor)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recMateriasPorProfesor_Result>("SP_recMateriasPorProfesor", id_profesorParameter);
        }
    
        public virtual ObjectResult<SP_recNoticiaPorId_Result> SP_recNoticiaPorId(Nullable<int> id_noticia)
        {
            var id_noticiaParameter = id_noticia.HasValue ?
                new ObjectParameter("id_noticia", id_noticia) :
                new ObjectParameter("id_noticia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recNoticiaPorId_Result>("SP_recNoticiaPorId", id_noticiaParameter);
        }
    
        public virtual ObjectResult<SP_recNoticias_Result> SP_recNoticias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recNoticias_Result>("SP_recNoticias");
        }
    
        public virtual ObjectResult<SP_recPadrePorCedula_Result> SP_recPadrePorCedula(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recPadrePorCedula_Result>("SP_recPadrePorCedula", cedulaParameter);
        }
    
        public virtual ObjectResult<SP_recPadrePorId_Result> SP_recPadrePorId(Nullable<int> id_padre)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recPadrePorId_Result>("SP_recPadrePorId", id_padreParameter);
        }
    
        public virtual ObjectResult<SP_recPadres_Result> SP_recPadres()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recPadres_Result>("SP_recPadres");
        }
    
        public virtual ObjectResult<SP_recPadresPorEstudiante_Result> SP_recPadresPorEstudiante(Nullable<int> id_estudiante)
        {
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recPadresPorEstudiante_Result>("SP_recPadresPorEstudiante", id_estudianteParameter);
        }
    
        public virtual ObjectResult<SP_recProfesores_Result> SP_recProfesores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recProfesores_Result>("SP_recProfesores");
        }
    
        public virtual ObjectResult<SP_recProfesoresConMaterias_Result> SP_recProfesoresConMaterias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recProfesoresConMaterias_Result>("SP_recProfesoresConMaterias");
        }
    
        public virtual ObjectResult<SP_recProfesoresPorMateria_Result> SP_recProfesoresPorMateria(Nullable<int> id_materia)
        {
            var id_materiaParameter = id_materia.HasValue ?
                new ObjectParameter("id_materia", id_materia) :
                new ObjectParameter("id_materia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recProfesoresPorMateria_Result>("SP_recProfesoresPorMateria", id_materiaParameter);
        }
    
        public virtual ObjectResult<SP_recProfesorPorId_Result> SP_recProfesorPorId(Nullable<int> id_profesor)
        {
            var id_profesorParameter = id_profesor.HasValue ?
                new ObjectParameter("id_profesor", id_profesor) :
                new ObjectParameter("id_profesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recProfesorPorId_Result>("SP_recProfesorPorId", id_profesorParameter);
        }
    
        public virtual ObjectResult<SP_recSecciones_Result> SP_recSecciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recSecciones_Result>("SP_recSecciones");
        }
    
        public virtual ObjectResult<SP_recSeccionesPorCiclo_Result> SP_recSeccionesPorCiclo(Nullable<int> id_ciclo)
        {
            var id_cicloParameter = id_ciclo.HasValue ?
                new ObjectParameter("id_ciclo", id_ciclo) :
                new ObjectParameter("id_ciclo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recSeccionesPorCiclo_Result>("SP_recSeccionesPorCiclo", id_cicloParameter);
        }
    
        public virtual ObjectResult<SP_recSeccionPorId_Result> SP_recSeccionPorId(Nullable<int> id_seccion)
        {
            var id_seccionParameter = id_seccion.HasValue ?
                new ObjectParameter("id_seccion", id_seccion) :
                new ObjectParameter("id_seccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recSeccionPorId_Result>("SP_recSeccionPorId", id_seccionParameter);
        }
    
        public virtual ObjectResult<SP_recUsuarioPorId_Result> SP_recUsuarioPorId(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recUsuarioPorId_Result>("SP_recUsuarioPorId", id_usuarioParameter);
        }
    
        public virtual ObjectResult<SP_recUsuarios_Result> SP_recUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_recUsuarios_Result>("SP_recUsuarios");
        }
    
        public virtual int SP_relPadreEstudiante(Nullable<int> id_padre, Nullable<int> id_estudiante)
        {
            var id_padreParameter = id_padre.HasValue ?
                new ObjectParameter("id_padre", id_padre) :
                new ObjectParameter("id_padre", typeof(int));
    
            var id_estudianteParameter = id_estudiante.HasValue ?
                new ObjectParameter("id_estudiante", id_estudiante) :
                new ObjectParameter("id_estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_relPadreEstudiante", id_padreParameter, id_estudianteParameter);
        }
    }
}
